# Add source files here
EXECUTABLE := HelloWorld
# # CUDA source files (compiled with cudacc)
CUFILES := HelloWorld.cu
# # CUDA dependency files
CU_DEPS := \
HelloWorld_kernel.cu \
#
# # C/C++ source files (compiled with gcc / c++)
CCFILES := \
#
#
#
# ################################################################################
# # Rules and targets
#
include ../../common/common.mk
