CC=gcc
CFLAGS=-Wall

#all: bookorder

#bookorder: bookpre bookmain

#bookpre:
#	$(CC) $(CFLAGS) -c bookorder.c

#bookmain:
#	$(CC) $(CFLAGS) -o bookorder main.c bookorder.c

all:
	$(CC) $(CFLAGS) -o bookorder main.c bookorder.c filelength.c populate_buffer.c
